### ISSUE TITLE
pack script deletes a file under version control

### ISSUE THREAD

**Issue by boneskull** [hackmdio/hackmd-cli#15]
`oclif.manifest.json` is under version control, but `postpack` removes it.  either the `postpack` script is wrong, or `oclif.manifest.json` should not be under version control

**Comment by boneskull** [comment]
also, I'm not sure if you really want `postpack`/`prepack`, or just `prepublishOnly`

**Comment by Yukaii** [comment]
It's a script from oclif, and it seems that `oclif.manifest.json` should only be generated within the build phase and never been committed into version control.
